from __future__ import annotations

import json

from kaggle_agent.schema import SubmissionCandidate, WorkspaceConfig, WorkspaceState
from kaggle_agent.utils import atomic_write_text, ensure_directory, now_utc_iso, slugify


def submission_dedupe_key(run_id: str) -> str:
    return f"submission_candidate:{run_id}"


def build_submission_candidate(config: WorkspaceConfig, state: WorkspaceState, run_id: str) -> SubmissionCandidate:
    run = next(item for item in state.runs if item.run_id == run_id)
    experiment = next(item for item in state.experiments if item.id == run.experiment_id)
    timestamp = now_utc_iso()
    dedupe_key = submission_dedupe_key(run.run_id)
    existing = next(
        (item for item in state.submissions if item.dedupe_key == dedupe_key or item.source_run_id == run.run_id),
        None,
    )
    submission_id = existing.id if existing is not None else f"submission-{slugify(run.run_id)}"
    if existing is not None and existing.notebook_dir:
        existing_root = config.root / existing.notebook_dir
        root = existing_root if existing_root.is_absolute() else existing_root.resolve()
    else:
        root = config.artifact_path("submissions", submission_id)
    ensure_directory(root)
    kernel_id = f"{config.kaggle.username}/{config.kaggle.kernel_slug}" if config.kaggle.username else config.kaggle.kernel_slug
    notebook_payload = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# {config.competition.name} Submission Candidate\n",
                    f"- Run id: `{run.run_id}`\n",
                    f"- Experiment id: `{experiment.id}`\n",
                    f"- Primary metric: `{run.primary_metric_name}={run.primary_metric_value}`\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Fill in the final Kaggle inference path here.\n",
                    "print('Submission candidate scaffold generated by kaggle_agent')\n",
                ],
            },
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    candidate = SubmissionCandidate(
        id=submission_id,
        source_run_id=run.run_id,
        experiment_id=experiment.id,
        status="candidate",
        primary_metric_name=run.primary_metric_name,
        primary_metric_value=run.primary_metric_value,
        secondary_metrics=dict(run.secondary_metrics),
        rationale=f"Auto-generated from {run.run_id}.",
        notebook_dir=str(root.relative_to(config.root)),
        created_at=timestamp,
        updated_at=timestamp,
        dedupe_key=dedupe_key,
    )
    kernel_metadata = {
        "id": kernel_id,
        "title": config.kaggle.kernel_slug.replace("-", " ").title(),
        "code_file": "notebook.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": config.kaggle.is_private,
        "enable_gpu": config.kaggle.enable_gpu,
        "competition_sources": [config.competition.slug],
        "dataset_sources": [config.kaggle.model_dataset_id] if config.kaggle.model_dataset_id else [],
    }
    atomic_write_text(root / "notebook.ipynb", json.dumps(notebook_payload, indent=2) + "\n")
    atomic_write_text(root / "kernel-metadata.json", json.dumps(kernel_metadata, indent=2) + "\n")
    atomic_write_text(
        root / "README.md",
        "\n".join(
            [
                f"# {candidate.id}",
                "",
                f"- Source run: `{run.run_id}`",
                f"- Primary metric: `{run.primary_metric_name}={run.primary_metric_value}`",
                "",
                "Replace the placeholder notebook code before pushing to Kaggle.",
            ]
        )
        + "\n",
    )
    if existing is None:
        state.submissions.append(candidate)
        return candidate
    existing.updated_at = timestamp
    existing.dedupe_key = dedupe_key
    existing.notebook_dir = candidate.notebook_dir
    existing.primary_metric_name = candidate.primary_metric_name
    existing.primary_metric_value = candidate.primary_metric_value
    existing.secondary_metrics = candidate.secondary_metrics
    existing.status = candidate.status
    existing.rationale = candidate.rationale
    return existing
